### PR TITLE
Remove trailing whitespace

### PR DESCRIPTION
**Pull request by gmarkall**
This is a test.

### CODE REVIEW

**Comment by kynan** [comment]
What were you testing there?

**Comment by gmarkall** [comment]
I was checking that Github still closes a PR if you do a fast-forward merge of the branch and then push to master - and it does :-)

**Comment by kynan** [comment]
That's good to know :)

**Comment by gmarkall** [comment]
Yeah - I had just told someone it did that, so I thought I better check. :-)

**Pull request merged**
